### ISSUE TITLE
Resolving from cache fails when cache dir rights are applied with ACL's

### ISSUE THREAD

**Issue by FeatCrush** [mamba-org/mamba#1123]
OS : RHEL7
Mamba version : 0.15.2
Conda version : 4.10.3

## How to replicate :

1. Create cache dir
```
mkdir -p /tmp/cache/conda
```
2. Add ACL's for your user
```
 setfacl -m d:u:<user>:rwx /tmp/cache/conda/
 setfacl -m u:<user>:rwx /tmp/cache/conda/
```
3. Change folder owner to root to rely solely on ACL's
```
chown root:root /tmp/cache/conda/
```

## Expected behavior 

`conda create -n test python`
The command works fine and the cache is populated with downloaded packages.

## Actual behavior
`mamba create -n test python`
Resolving breaks while accessing cache registry
```
RuntimeError: Operation not permitted: '/tmp/cache/conda/cache/f7c32d1b.json'
```

In our use case, package cache has to be accesible to mutiple groups.
We cannot rely solely on user:group rights.

**Comment by wolfv** [comment]
Hmm, I haven't used ACL's myself. Any idea if we'd need to change the C++ code for this to work? I would have thought that a regular std::ofstream("myfile"); works fine...

Do you have the permission to create folders etc. in that cache location?

**Comment by FeatCrush** [comment]
I was able to replicate the behavior in a centos7 docker container 
This is my new test process :
1.  Create two users (toto and titi in my case)
2. Create conda env with `toto` user 
3. Check that cache is populated (OK) 
4. Create same env with mamba, cache is hit (OK)
5. Switch to user `titi`
6. Create conda env with conda, cache is hit (OK)
7. Create same env with mamba (KO)

It seems that the cache files **have to be owned by the exec user**

ACL's for the problematic file 
```
# file: var/cache/conda/cache/28dc370b.json
# owner: toto
# group: toto
user::rwx
user:toto:rwx
user:titi:rwx
group::r-x
mask::rwx
other::r--
```

Stacktrace : 

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/mamba.py", line 920, in exception_converter
        raise e
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/mamba.py", line 914, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/mamba.py", line 873, in _wrapped_main
        result = do_call(args, p)
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/mamba.py", line 755, in do_call
        exit_code = create(args, parser)
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/mamba.py", line 658, in create
        return install(args, parser, "create")
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/mamba.py", line 529, in install
        index = load_channels(pool, channels, repos)
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/utils.py", line 119, in load_channels
        index = get_index(
      File "/home/titi/.conda/envs/mamba/lib/python3.9/site-packages/mamba/utils.py", line 100, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Operation not permitted: '/var/cache/conda/cache/14e80fbd.json'

`$ /home/titi/.conda/envs/mamba/bin/mamba create -vvv -n test python numpy`
```

I hope i do not miss something obvious

**Comment by FeatCrush** [comment]
Ok i found the issue with strace

```
utimensat(AT_FDCWD, "/var/cache/conda/pkgs/cache/f7c32d1b.json", [UTIME_OMIT, {tv_sec=1628778033, tv_nsec=526229681} /* 2021-08-12T16:20:33.526229681+0200 */], AT_SYMLINK_NOFOLLOW) = -1 EPERM (Operation not permitted)
```

The validity of repodata and solv files rely on the time of last modification.
To update those values the c++ implementation use the [`last_write_time` func](https://github.com/mamba-org/mamba/blob/a1f7f9b835ca178485996d6e7402767a043151e6/src/core/subdirdata.cpp#L228)

This function only works if the target file is owned by the user or is privileged, as documented [here](https://man7.org/linux/man-pages/man2/utimensat.2.html)

I disabled those calls and the issue is resolved.

We could solve the issue by changing the method to update the time of last modification
Maybe write something useless at the end of file ? 

I'm not proficient in C++ so if you have a better solution let me now :+1:

**Comment by wolfv** [comment]
hey wow, thanks for investigating! this makes things a lot more clear to me ... will have to look into what we can do here.

**Comment by FeatCrush** [comment]
I found out that `utimensat` sets 'last write time' to now if not specified. 
So i just replaced the problematic calls by a direct ref to `utimensat`.
Works fine in my setup, let me know what you think of this PR.

**Comment by wolfv** [comment]
If someone can finish the PR I'm happy to merge it!

**Comment by adriendelsalle** [comment]
We recently implemented multiple package cache but also use of read-only ones.
From master branch I can't reproduce the issue, I'm running:


```bash
$ docker run -it --rm -v <path-to-build-dir>/micromamba:/bin/micromamba centos:7
```
where `<path-to-build-dir>` is where I'm building `micromamba`, fully statically linked for that test.

Then I created the cache and set ACLs + changed owner to root:
```bash
mkdir /tmp/mamba_cache
adduser toto
adduser titi
setfacl -m d:u:toto:rwx /tmp/mamba_cache/
setfacl -m d:u:titi:rwx /tmp/mamba_cache/
setfacl -m u:toto:rwx /tmp/mamba_cache/
setfacl -m u:titi:rwx /tmp/mamba_cache/
chown -R root:root /tmp/mamba_cache/
```
Checking the ownership and permissions:
```bash
$ ls -la /tmp/mamba_cache/
total 6008
drwxrwxr-x+ 0 root root    4096 Nov  3 16:16 .
drwxrwxrwt   1 root root    4096 Nov  3 16:16 ..

$ getfacl /tmp/mamba_cache/
getfacl: Removing leading '/' from absolute path names
# file: tmp/mamba_cache/
# owner: root
# group: root
user::rwx
user:toto:rwx
user:titi:rwx
group::r-x
mask::rwx
other::r-x
default:user::rwx
default:user:toto:rwx
default:user:titi:rwx
default:group::r-x
default:mask::rwx
default:other::r-x
```

User `toto`:
```bash
$ su toto
$ CONDA_PKGS_DIRS=/tmp/mamba_cache micromamba create -n test xtensor -c conda-forge -y -vvv
(...)
DEBUG   Checking if '/tmp/mamba_cache' is writable
DEBUG   '/tmp/mamba_cache' writable
DEBUG   Finalized transfer of 'https://conda.anaconda.org/conda-forge/noarch/repodata.json'
DEBUG   Locking directory '/tmp/mamba_cache/cache'
TRACE   Lockfile created at '/tmp/mamba_cache/cache/mamba.lock'
(...)
TRACE   linking 'include/xtensor.hpp'
TRACE   hard-linked '/tmp/mamba_cache/xtensor-0.24.0-h4bd325d_0/include/xtensor.hpp'
         --> '/home/toto/micromamba/envs/test/include/xtensor.hpp'
(...)
```

User `titi`:
```bash
$ su titi
$ CONDA_PKGS_DIRS=/tmp/mamba_cache micromamba create -n test xtensor -c conda-forge -y -vvv
(...)
DEBUG   Locking directory '/tmp/mamba_cache/cache'
TRACE   Lockfile created at '/tmp/mamba_cache/cache/mamba.lock'
DEBUG   Successfully locked
INFO    Found cache at '/tmp/mamba_cache/cache/b556ea5a.json'
DEBUG   Using JSON cache
TRACE   Cache age: 31/1200s
DEBUG   Using SOLV cache
TRACE   Cache age: 29s
DEBUG   Unlocking '/tmp/mamba_cache/cache'
TRACE   Removing file '/tmp/mamba_cache/cache/mamba.lock'
(...)
DEBUG   Verify cache '/tmp/mamba_cache' for package extracted directory 'xtensor-0.24.0-h4bd325d_0'
DEBUG   'xtensor-0.24.0-h4bd325d_0' extracted directory cache is valid
(...)
TRACE   linking 'include/xtensor.hpp'
TRACE   hard-linked '/tmp/mamba_cache/xtensor-0.24.0-h4bd325d_0/include/xtensor.hpp'
         --> '/home/titi/micromamba/envs/test/include/xtensor.hpp'
(...)
```

A final check that the inodes match:
```bash
$ ll -i /tmp/mamba_cache/xtensor-0.24.0-h4bd325d_0/include/xtensor.hpp 
974589 -rw-rw-r--+ 3 toto toto 2264 Oct 18 19:27 /tmp/mamba_cache/xtensor-0.24.0-h4bd325d_0/include/xtensor.hpp

$ ll -i /home/toto/micromamba/envs/test/include/xtensor.hpp 
974589 -rw-rw-r--+ 3 toto toto 2264 Oct 18 19:27 /home/toto/micromamba/envs/test/include/xtensor.hpp

$ ll -i /home/titi/micromamba/envs/test/include/xtensor.hpp 
974589 -rw-rw-r--+ 3 toto toto 2264 Oct 18 19:27 /home/titi/micromamba/envs/test/include/xtensor.hpp
```

Now if I create a new user `tata`, it won't have write permission in that cache.
- if the cache is still valid (not expired), everything works fine
  - notice that linking uses copy instead of hard-link

```bash
$ su tata
$ CONDA_PKGS_DIRS=/tmp/mamba_cache micromamba create -n test xtensor -c conda-forge -y -vvv
(...)
INFO    Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/noarch/repodata.json'
DEBUG   Locking directory '/tmp/mamba_cache/cache'
ERROR   Could not open lockfile '/tmp/mamba_cache/cache/mamba.lock'
TRACE   Removing file '/tmp/mamba_cache/cache/mamba.lock'
WARNING LockFile creation for path '/tmp/mamba_cache/cache' failed, continuing without it
INFO    Found cache at '/tmp/mamba_cache/cache/ddfd5f96.json'
DEBUG   Using JSON cache
TRACE   Cache age: 670/1200s
DEBUG   Using SOLV cache
TRACE   Cache age: 661s
(...)
DEBUG   Verify cache '/tmp/mamba_cache' for package extracted directory 'xtensor-0.24.0-h4bd325d_0'
DEBUG   'xtensor-0.24.0-h4bd325d_0' extracted directory cache is valid
(...)
TRACE   linking 'include/xtensor.hpp'
TRACE   copied '/tmp/mamba_cache/xtensor-0.24.0-h4bd325d_0/include/xtensor.hpp'
         --> '/home/tata/micromamba/envs/test/include/xtensor.hpp'
(...)
```

- if the cache expired, which is simulated with `--repodata-ttl=0`, providing the small fix I just pushed in https://github.com/mamba-org/mamba/pull/1253:
  - it will fail if you don't provide a writable cache path

```bash
$ su tata
$ CONDA_PKGS_DIRS=/tmp/mamba_cache micromamba create -n test xtensor -c conda-forge -y -vvv --repodata-ttl=0
(...)
DEBUG   Checking if '/tmp/mamba_cache' is writable
TRACE   '/tmp/mamba_cache/urls.txt' exists, checking if writable
DEBUG   '/tmp/mamba_cache' not writable
INFO    Cache is still valid
ERROR   Could not find any writable cache directory for repodata file
* Closing connection 0
ERROR   Non-writable cache error.
```

  - it will work if you provide a writable cache path

```
```bash
$ su tata
$ CONDA_PKGS_DIRS=/tmp/mamba_cache,~/cache micromamba create -n test xtensor -c conda-forge -y -vvv --repodata-ttl=0
(...)
DEBUG   Checking if '/tmp/mamba_cache' is writable
TRACE   '/tmp/mamba_cache/urls.txt' exists, checking if writable
DEBUG   '/tmp/mamba_cache' not writable
DEBUG   Checking if '/home/tata/cache' is writable
TRACE   Cache path does not exists
DEBUG   '/home/tata/cache' writable
INFO    Cache is still valid
DEBUG   Copying repodata cache files from '/tmp/mamba_cache' to '/home/tata/cache'
(...)
TRACE   linking 'include/xtensor.hpp'
TRACE   copied '/tmp/mamba_cache/xtensor-0.24.0-h4bd325d_0/include/xtensor.hpp'
         --> '/home/tata/micromamba/envs/test/include/xtensor.hpp'
(...)
```

Maybe we could think to change a bit the logic when linking against a read-only cache is a writable one is provided to avoid multiple copy: copy from the read-only to the writable cache then hard-link from that cache to the prefix.
But it's a different issue I'll open.

@FeatCrush @jwwatts please give me some feedbacks about that :)

**Comment by adriendelsalle** [comment]
@FeatCrush @jwwatts I'm closing this issue, feel free to re-open it if you can reproduce this issue with version >= `0.18.0`

**Comment by Porkchop1414** [comment]
Running 0.19.0 and still seeing permission errors around the package cache, unfortunately.
`RuntimeError: Operation not permitted: '/opt/conda/pkgs/cache/b63425f9.json'`

**Comment by wolfv** [comment]
@Porkchop1414 can give more details on your specific scenario?!?!

**Comment by Porkchop1414** [comment]
CentOS 7.4 environment with umask 0022, distribution installed in /opt/conda owned by appuser:users. Regular users members of the group, all directories setgid and ACLs set default:group:users:rwx. We want appuser to be able to create and update environment, but have other files and updates made by other users not conflict.

**Comment by pmenzel** [comment]
having occasionally the same issue with mamba 0.19.1, conda 4.11.0 on Ubuntu 20.04, with shared conda folder for all users, which are in the same group.

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/miniconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/miniconda3/lib/python3.8/site-packages/mamba/mamba_env.py", line 45, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/opt/conda/miniconda3/lib/python3.8/site-packages/mamba/utils.py", line 122, in load_channels
        index = get_index(
      File "/opt/conda/miniconda3/lib/python3.8/site-packages/mamba/utils.py", line 103, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Operation not permitted: '/opt/conda/miniconda3/pkgs/cache/976d321b.json'
```

**Comment by coroa** [comment]
Still exists on mamba 1.0.0, Ubuntu.

Cache is owned by different user, writability is guaranteed by shared group kept by the setgid bit. Mamba fails when trying to update the timestamp.

```
Looking for: ['ipython', 'ipykernel', 'pypsa']

filesystem error: cannot set file time: Operation not permitted [/opt/mambaforge/pkgs/cache/09cdf8bf.json]

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 886, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = create(args, parser)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 630, in create
        return install(args, parser, "create")
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 129, in load_channels
        index = get_index(
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: filesystem error: cannot set file time: Operation not permitted [/opt/mambaforge/pkgs/cache/09cdf8bf.json]
```

**Comment by coroa** [comment]
Contrary to https://github.com/mamba-org/mamba/issues/1123#issuecomment-959739126 ,

> * it will work if you provide a writable cache path

will not help here, since `mamba` determines the cache directory (correctly) to be writable:

❯ CONDA_PKGS_DIRS=/opt/mambaforge/pkgs,/tmp/cache mamba create -n test3 python -c conda-forge -y -v

Looking for: ['python']

info     libmamba Reading cache files '/tmp/tmpatv539gj.*' for repo index 'installed'
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/linux-64/repodata.json'
info     libmamba Found cache at '/opt/mambaforge/pkgs/cache/497deca9.json'
info     libmamba No valid cache found
info     libmamba Expired cache (or invalid mod/etag headers) found at '/opt/mambaforge/pkgs'
info     libmamba Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/noarch/repodata.json'
info     libmamba Found cache at '/opt/mambaforge/pkgs/cache/09cdf8bf.json'
info     libmamba No valid cache found
info     libmamba Expired cache (or invalid mod/etag headers) found at '/opt/mambaforge/pkgs'
info     libmamba Starting to download targets
[...]
libmamba Transfer done for 'conda-forge/noarch'
filesystem error: cannot set file time: Operation not permitted [/opt/mambaforge/pkgs/cache/09cdf8bf.json]

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 886, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = create(args, parser)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 630, in create
        return install(args, parser, "create")
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 129, in load_channels
        index = get_index(
      File "/opt/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 110, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: filesystem error: cannot set file time: Operation not permitted [/opt/mambaforge/pkgs/cache/09cdf8bf.json]
```
